# Generated by Django 3.0.2 on 2020-01-22 17:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='baz',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='weekday',
        ),
        migrations.AddField(
            model_name='target',
            name='email_time',
            field=models.TimeField(default=datetime.time(12, 0), verbose_name='Email time'),
        ),
        migrations.AddField(
            model_name='target',
            name='weekday',
            field=models.CharField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday')], default='0', max_length=20, verbose_name='Weekday'),
        ),
        migrations.CreateModel(
            name='SentBaz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Sent datetime')),
                ('baz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_to_targets', to='main.Baz', verbose_name='Baz')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_bazes', to='main.Target', verbose_name='Target')),
            ],
        ),
    ]
