# Generated by Django 3.0.2 on 2020-01-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_sample_create_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentbaz',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='Error message'),
        ),
        migrations.AddField(
            model_name='sentbaz',
            name='successful',
            field=models.BooleanField(default=False, verbose_name='Is email sending was successful'),
        ),
    ]
